# Generated by Django 4.2.7 on 2023-11-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarberia', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('Barbero', 'barbero'), ('Cliente', 'cliente')], default='Cliente', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
