# Generated by Django 4.2.7 on 2023-11-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarberia', '0003_usuarioform_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioForm',
            new_name='Usuario',
        ),
    ]
