# Generated by Django 4.2.7 on 2023-11-29 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarberia', '0004_rename_usuarioform_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
