# Generated by Django 4.2.7 on 2023-12-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarberia', '0009_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberia',
            name='insta',
            field=models.CharField(default='https://www.instagram.com/', max_length=100),
        ),
        migrations.AddField(
            model_name='barberia',
            name='maps',
            field=models.CharField(default='https://maps.app.goo.gl/4Z6tBPcvjYrki5nK8', max_length=100),
        ),
    ]
